import gsap from "gsap";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef } from "react";

export default function Home() {
	const boxRef = useRef();

	useEffect(() => {
		gsap.to(boxRef.current, { rotation: "+360" });
	});
	return (
		<div>
			<Head>
				<title>Gsap Examples</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div
				style={{
					display: " flex",
					alignItems: "center",
					justifyContent: " center",
					minHeight: "100vh",
				}}
			>
				<div
					className="box "
					style={{
						// height: "100vh",
						// width: "100vw",
						// placeItems: "center",
						// display: "grid",
						width: "100px",
						height: "100px",
						borderRadius: " 12px",
						display: "flex",
						alignItems: "center",
						justifyContent: "center",
						textAlign: "center",
						backgroundColor: "green",
						fontWeight: 600,
						color: "white",
					}}
					ref={boxRef}
				>
					Hello
				</div>
			</div>
		</div>
	);
}
